services:
  database:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yann
      POSTGRES_PASSWORD: api
      POSTGRES_DB: dev-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s

  database-ihm:
    image: adminer:5.4.1-standalone
    container_name: adminer
    ports:
      - "9090:8080"
    depends_on:
      database:
        condition: service_healthy

  log-aggregator:
    image: grafana/loki:3.6.3
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./tools/data/loki:/loki
      - ./tools/configurations/loki/local-config.yaml:/etc/loki/local-config.yaml
    depends_on:
      database:
        condition: service_healthy

  log-agent:
    image: grafana/alloy:v1.12.1
    container_name: alloy
    restart: unless-stopped
    ports:
      - "12345:12345"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./tools/configurations/alloy/config.alloy:/etc/alloy/config.alloy
      - ./tmp/logs:/tmp/logs
    depends_on:
      log-aggregator:
        condition: service_started

  dashboard:
    image: grafana/grafana:11.6.9
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_NABLE=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
    volumes:
      - ./tools/data/grafana/data:/var/lib/grafana
      - ./tools/data/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      log-aggregator:
        condition: service_started
      log-agent:
        condition: service_started
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        EOF
        /run.sh

volumes:
  dev_postgres_data:
